// Installs the cache-warm status line *around* whatever status line is already
// configured, and removes itself again without a trace.
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { HOME, readJson, writeJsonAtomic } from './lib.mjs';

const STATE = path.join(HOME, 'statusline.json');
const LAUNCHER = path.join(HOME, 'statusline-launcher.mjs');
const PLUGIN_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const MARK = 'statusline-launcher.mjs';

// The plugin directory moves on every plugin update, but settings.json should not
// have to change with it. So settings point at this small launcher in the state
// dir, and the SessionStart hook keeps `pluginRoot` in statusline.json current.
// If the plugin is gone, the launcher degrades to the user's own status line.
const LAUNCHER_SOURCE = `// Generated by claude-cache-warm. Remove with: ccw statusline uninstall
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
let state = {};
try { state = JSON.parse(fs.readFileSync(path.join(here, 'statusline.json'), 'utf8')); } catch {}
const impl = path.join(state.pluginRoot || '', 'scripts', 'statusline.mjs');
if (state.pluginRoot && fs.existsSync(impl)) {
  (await import(pathToFileURL(impl).href)).main();
} else if (state.wrapped?.command) {
  const r = spawnSync(state.wrapped.command, { shell: true, input: fs.readFileSync(0), encoding: 'utf8', timeout: 4000, windowsHide: true });
  process.stdout.write(r.stdout || '');
}
`;

/** Settings files that can carry a statusLine, highest precedence first. */
function candidates(cwd) {
  return [
    path.join(cwd, '.claude', 'settings.local.json'),
    path.join(cwd, '.claude', 'settings.json'),
    path.join(os.homedir(), '.claude', 'settings.json'),
  ].filter((f, i, all) => all.indexOf(f) === i);
}

function ourCommand() {
  // The status line shell may not have node on PATH; the installer's node certainly exists.
  return `"${process.execPath.replace(/\\/g, '/')}" "${LAUNCHER.replace(/\\/g, '/')}"`;
}

export function refreshPluginRoot() {
  const state = readJson(STATE);
  if (state && state.pluginRoot !== PLUGIN_ROOT) writeJsonAtomic(STATE, { ...state, pluginRoot: PLUGIN_ROOT });
}

export function statuslineStatus(cwd = process.cwd()) {
  const state = readJson(STATE);
  const active = candidates(cwd).find((f) => readJson(f)?.statusLine);
  const current = active ? readJson(active).statusLine : null;
  return {
    installed: !!current?.command?.includes(MARK),
    settingsFile: active || null,
    currentCommand: current?.command || null,
    wrapped: state?.wrapped?.command || null,
    placement: state?.placement || 'append',
  };
}

export function installStatusline({ cwd = process.cwd(), file, placement } = {}) {
  // Wrap the status line that is actually in effect; with none anywhere, use the user settings.
  const target = file ? path.resolve(file) : candidates(cwd).find((f) => readJson(f)?.statusLine) || path.join(os.homedir(), '.claude', 'settings.json');
  const settings = readJson(target, null) ?? (fs.existsSync(target) ? null : {});
  if (settings === null) throw new Error(`${target} is not valid JSON; not touching it`);

  const previous = readJson(STATE) || {};
  const existing = settings.statusLine || null;
  const alreadyOurs = !!existing?.command?.includes(MARK);
  // Re-running install must not wrap our own launcher.
  const wrapped = alreadyOurs ? previous.wrapped || null : existing;

  fs.mkdirSync(HOME, { recursive: true });
  fs.writeFileSync(LAUNCHER, LAUNCHER_SOURCE);
  writeJsonAtomic(STATE, { pluginRoot: PLUGIN_ROOT, settingsFile: target, wrapped, placement: placement || previous.placement || 'append' });

  if (!alreadyOurs) {
    if (fs.existsSync(target)) fs.copyFileSync(target, `${target}.ccw-backup`);
    settings.statusLine = {
      ...(existing || {}),
      type: 'command',
      command: ourCommand(),
      // the countdowns should keep moving while the session sits idle
      refreshInterval: existing?.refreshInterval || 30,
    };
    writeJsonAtomic(target, settings);
  }
  return { settingsFile: target, wrapped: wrapped?.command || null, alreadyInstalled: alreadyOurs };
}

export function uninstallStatusline() {
  const state = readJson(STATE);
  if (!state?.settingsFile) throw new Error('the cache-warm status line is not installed');
  const settings = readJson(state.settingsFile, null);
  if (settings?.statusLine?.command?.includes(MARK)) {
    if (state.wrapped) settings.statusLine = state.wrapped;
    else delete settings.statusLine;
    writeJsonAtomic(state.settingsFile, settings);
  }
  fs.rmSync(STATE, { force: true });
  fs.rmSync(LAUNCHER, { force: true });
  return { settingsFile: state.settingsFile, restored: state.wrapped?.command || null };
}
