// Installs the cache-warm status line *around* whatever status line is already
// configured, and removes itself again without a trace.
//
// Claude Code takes the statusLine from the most specific settings file that has
// one: <project>/.claude/settings.local.json, then <project>/.claude/settings.json,
// then ~/.claude/settings.json. Installing into the user file covers every folder
// that doesn't define its own; `--file` targets one of the project files instead.
// Each install remembers the command it wrapped, so several can coexist.
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { HOME, readJson, writeJsonAtomic } from './lib.mjs';

export const STATE = path.join(HOME, 'statusline.json');
const LAUNCHER = path.join(HOME, 'statusline-launcher.mjs');
const PLUGIN_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const MARK = 'statusline-launcher.mjs';
export const DEFAULT_REFRESH_SECONDS = 5;

const configDir = () => process.env.CLAUDE_CONFIG_DIR || path.join(os.homedir(), '.claude');
const userSettings = () => path.join(configDir(), 'settings.json');
const fwd = (p) => p.replace(/\\/g, '/');

// The plugin directory moves on every plugin update, but settings files should not
// have to change with it. So settings point at this small launcher in the state
// dir. It runs the copy of the plugin Claude Code currently has installed (from
// installed_plugins.json), so sessions still running an older copy can't drag it
// back. If the plugin is gone, it degrades to the user's own status line.
const LAUNCHER_VERSION = 3;
const LAUNCHER_SOURCE = `// Generated by claude-cache-warm (launcher v${LAUNCHER_VERSION}). Remove with: ccw statusline uninstall
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const read = (f) => { try { return JSON.parse(fs.readFileSync(f, 'utf8')); } catch { return null; } };
const state = read(path.join(here, 'statusline.json')) || {};
const installs = Object.values(state.installs || {});
const install = (state.installs || {})[process.argv[2]] || (installs.length === 1 ? installs[0] : null) || { wrapped: state.wrapped, placement: state.placement };
const configDir = process.env.CLAUDE_CONFIG_DIR || path.join(os.homedir(), '.claude');
const installed = read(path.join(configDir, 'plugins', 'installed_plugins.json'));
const entry = (installed?.plugins || installed || {})['cache-warm@claude-cache-warm'];
const roots = [...(Array.isArray(entry) ? entry.map((e) => e.installPath) : []), state.pluginRoot].filter(Boolean);
const impl = roots.map((r) => path.join(r, 'scripts', 'statusline.mjs')).find((f) => fs.existsSync(f));
if (impl) {
  await (await import(pathToFileURL(impl).href)).main(install);
} else if (install.wrapped?.command) {
  const r = spawnSync(install.wrapped.command, { shell: true, input: fs.readFileSync(0), encoding: 'utf8', timeout: 8000, windowsHide: true });
  process.stdout.write(r.stdout || '');
}
`;

const keyFor = (settingsFile) =>
  path.resolve(settingsFile) === path.resolve(userSettings()) ? 'user' : crypto.createHash('sha1').update(path.resolve(settingsFile).toLowerCase()).digest('hex').slice(0, 8);

function loadState() {
  const s = readJson(STATE, null);
  if (!s) return { version: 2, installs: {} };
  if (s.installs) return s;
  // 0.2 layout: a single install, no key
  const installs = s.settingsFile ? { [keyFor(s.settingsFile)]: { settingsFile: s.settingsFile, wrapped: s.wrapped || null, placement: s.placement || 'append' } } : {};
  return { version: 2, pluginRoot: s.pluginRoot, installs };
}

// cache-warm 0.2's status line code (still run by sessions that haven't updated) reads a
// single top-level `wrapped`/`placement`; mirror the primary install there.
function saveState(state) {
  const primary = state.installs.user || Object.values(state.installs)[0] || {};
  writeJsonAtomic(STATE, { ...state, version: 2, wrapped: primary.wrapped || null, placement: primary.placement || 'append', settingsFile: primary.settingsFile });
}

function ourCommand(key) {
  // Forward slashes: on Windows Claude Code runs this through Git Bash, which eats backslashes.
  // The installer's own node is used because the status line shell may not have node on PATH.
  return `"${fwd(process.execPath)}" "${fwd(LAUNCHER)}" ${key}`;
}

function writeLauncher() {
  fs.mkdirSync(HOME, { recursive: true });
  let current = '';
  try {
    current = fs.readFileSync(LAUNCHER, 'utf8');
  } catch {
    // first install
  }
  if (current !== LAUNCHER_SOURCE) fs.writeFileSync(LAUNCHER, LAUNCHER_SOURCE);
}

/** SessionStart: keep an installed launcher current. Does nothing when the status line isn't installed. */
export function refreshStatuslineLauncher() {
  try {
    if (!fs.existsSync(STATE)) return;
    const state = loadState();
    writeLauncher();
    if (!state.pluginRoot || !fs.existsSync(path.join(state.pluginRoot, 'scripts', 'statusline.mjs')) || !readJson(STATE)?.installs) {
      saveState({ ...state, pluginRoot: PLUGIN_ROOT });
    }
  } catch {
    // the status line is a nicety; never fail a hook over it
  }
}

/** Settings files under `cwd` that would shadow a user-level status line. */
function shadowing(cwd) {
  return [path.join(cwd, '.claude', 'settings.local.json'), path.join(cwd, '.claude', 'settings.json')]
    .filter((f) => path.resolve(f) !== path.resolve(userSettings()))
    .filter((f) => readJson(f)?.statusLine);
}

export function statuslineStatus(cwd = process.cwd()) {
  const state = loadState();
  const inEffect = [...shadowing(cwd), userSettings()].find((f) => readJson(f)?.statusLine) || null;
  const current = inEffect ? readJson(inEffect).statusLine : null;
  return {
    installs: Object.entries(state.installs).map(([key, i]) => ({ key, ...i, wrapped: i.wrapped?.command || null, active: !!readJson(i.settingsFile)?.statusLine?.command?.includes(MARK) })),
    inEffect,
    inEffectIsOurs: !!current?.command?.includes(MARK),
    currentCommand: current?.command || null,
  };
}

export function installStatusline({ cwd = process.cwd(), file, placement, refreshSeconds = DEFAULT_REFRESH_SECONDS } = {}) {
  const target = path.resolve(file || userSettings());
  const settings = readJson(target, null) ?? (fs.existsSync(target) ? null : {});
  if (settings === null) throw new Error(`${target} is not valid JSON; not touching it`);

  const state = loadState();
  const key = keyFor(target);
  const existing = settings.statusLine || null;
  const alreadyOurs = !!existing?.command?.includes(MARK);
  // Re-running install must not wrap our own launcher.
  const wrapped = alreadyOurs ? state.installs[key]?.wrapped || null : existing;

  writeLauncher();
  state.pluginRoot = PLUGIN_ROOT;
  state.installs[key] = { settingsFile: target, wrapped, placement: placement || state.installs[key]?.placement || 'append', installedAt: Date.now() };
  saveState(state);

  if (!alreadyOurs && fs.existsSync(target)) fs.copyFileSync(target, `${target}.ccw-backup`);
  const { command, refreshInterval, ...rest } = existing || {};
  settings.statusLine = {
    ...rest,
    type: 'command',
    command: ourCommand(key),
    // Countdowns should tick while the session sits idle; events alone go quiet then.
    refreshInterval: refreshSeconds,
  };
  writeJsonAtomic(target, settings);
  const shadowedBy = file ? [] : shadowing(cwd).filter((f) => !readJson(f)?.statusLine?.command?.includes(MARK));
  return { settingsFile: target, wrapped: wrapped?.command || null, alreadyInstalled: alreadyOurs, shadowedBy };
}

/** Restore what each install wrapped. With `file`, only that settings file. */
export function uninstallStatusline({ file } = {}) {
  const state = loadState();
  const keys = file ? [keyFor(file)] : Object.keys(state.installs);
  if (!keys.some((k) => state.installs[k])) throw new Error('the cache-warm status line is not installed there');
  const restored = [];
  for (const key of keys) {
    const inst = state.installs[key];
    if (!inst) continue;
    const settings = readJson(inst.settingsFile, null);
    if (settings?.statusLine?.command?.includes(MARK)) {
      if (inst.wrapped) settings.statusLine = inst.wrapped;
      else delete settings.statusLine;
      writeJsonAtomic(inst.settingsFile, settings);
    }
    restored.push({ settingsFile: inst.settingsFile, restored: inst.wrapped?.command || null });
    delete state.installs[key];
  }
  if (Object.keys(state.installs).length) saveState(state);
  else {
    fs.rmSync(STATE, { force: true });
    fs.rmSync(LAUNCHER, { force: true });
  }
  return restored;
}
